name: Python pep8 check and test

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black blackdoc isort
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Python Lint
      run: |
        black --check *.py 
        blackdoc --check *.py
        isort --check *.py --profile black
        
    - name: Test with pytest
      run: |
        if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
          pytest
        else
          echo "No tests found. Skipping..."
        fi
